language: c

compiler:
  - gcc
  - clang

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq --no-install-recommends check valgrind

script:
  - autoreconf -i
  - ./configure
  - make -j2 memcheck
  - make distcheck
